
  CREATE TABLE "DOTORY"."DT_BOARD" 
   (	"BOARD_ID" NUMBER NOT NULL ENABLE, 
	"BOARD_TITLE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"BOARD_CONTENT" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"BOARD_DATE" DATE NOT NULL ENABLE, 
	"BOARD_UPDATE" DATE, 
	"BOARD_CNT" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"MEMBER_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "DT_BOARD_PK" PRIMARY KEY ("BOARD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "DT_BOARD_FK1" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "DOTORY"."DT_MEMBER" ("MEMBER_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "DOTORY"."DT_BOARD"."BOARD_ID" IS '게시글
아이디';
   COMMENT ON COLUMN "DOTORY"."DT_BOARD"."BOARD_TITLE" IS '게시글제목';
   COMMENT ON COLUMN "DOTORY"."DT_BOARD"."BOARD_CONTENT" IS '게시글내용
';
   COMMENT ON COLUMN "DOTORY"."DT_BOARD"."BOARD_DATE" IS '등록날짜';
   COMMENT ON COLUMN "DOTORY"."DT_BOARD"."BOARD_UPDATE" IS '수정날짜';
   COMMENT ON COLUMN "DOTORY"."DT_BOARD"."BOARD_CNT" IS '게시글조회수';
   COMMENT ON COLUMN "DOTORY"."DT_BOARD"."MEMBER_ID" IS '회원아이디';

